# 参考：https://qiita.com/shtnkgm/items/6dd756aa14926736c6f5

# Lint対象に追加するパス
included:
- messageTodo

# Lint対象から除外するパス
excluded:
- Carthage
- Pods
- messageTodoTests
- messageTodoUITests

# 基本的に全てのオプトインルールを有効化した上で、無効にしたいもののみdisabled_rulesに欄に記載し、無効化しています。

# 無効にするルール
disabled_rules:
- force_cast
- trailing_whitespace
- force_try
- function_parameter_count # 引数を6個以上用いたいため

# opt-inルールの中で無効にするルール
- conditional_returns_on_newline # ガード文などは簡潔に一行で記述したいため
- discouraged_optional_collection # PHImageManagerの既存仕様のため
- explicit_enum_raw_value # 暗黙的なraw値で問題ないため
- explicit_type_interface # 型推論を利用したいため
- fatal_error_message # メッセージは不要なため
- file_header # ヘッダには特に決まりがないため
- lower_acl_than_parent # 対応不可のため
- no_extension_access_modifier # extension_access_modifierを優先するため
- no_grouping_extension # グルーピングにextensionを利用したいため
- strict_fileprivate # fileprivateを利用したいため
- switch_case_on_newline # caseと同じ行に記述したいため
- trailing_closure # RxSwiftのOnNextでwarningが出るため


# defaultルール以外にopt-inから採用するルール
opt_in_rules:
- anyobject_protocol
- array_init
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_first_not_nil
- discouraged_object_literal
- empty_count
- empty_string
- identical_operands
- joined_default_parameter
- last_where
- legacy_random
- legacy_multiple
- lower_acl_than_parent
- modifier_order
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- private_action
- prohibited_super_call
- redundant_nil_coalescing
- trailing_closure
# - unavailable_function
- unused_import
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces

# 1行の文字列制限
line_length:
- 200   # warning
- 300   # error

# 型の行数制限
type_body_length:
- 400   # warning
- 600   # error

# 1ファイルの行数制限
file_length:
- 500   # warning
- 1000  # error

# メソッドの行数制限
function_body_length:
- 100   # warning
- 200   # error

type_name:
  min_length: 1
  max_length: 40

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - x
    - y
    - vc
    - on
  reporter: "xcode"
